export const routes = {
  SPLASH: 'SPLASH',
  HOME: 'HOME',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  PROFILE: 'PROFILE',
  SETTINGS: 'SETTINGS',
  ABOUT: 'ABOUT',
  BOTTOM_TAB: 'BOTTOM_TAB',
  HISTORY: 'HISTORY',
};
